server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

appDescription: "Pragma Powerup"
appVersion: "1.0.0"