server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka